apiVersion: v1
kind: Service
metadata:
  labels:
    app: admission-registry
  name: webhook
  namespace: zhenghongfei
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  selector:
    app: admission-registry
