apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-registry-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-registry-clusterrole
rules:
  - verbs: ["*"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    apiGroups: ["admissionregistration.k8s.io"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-registry-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-registry-clusterrole
subjects:
  - kind: ServiceAccount
    name: admission-registry-sa
    namespace: default

#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: admission-registry
#  labels:
#    app: admission-registry
#spec:
#  selector:
#    matchLabels:
#      app: admission-registry
#  template:
#    metadata:
#      labels:
#        app: admission-registry
#    spec:
#      serviceAccountName: admission-registry-sa
#      containers:
#        - name: webhook
#          image: docker.io/zheng199512/webhook-example:v1
#          imagePullPolicy: IfNotPresent
#          env:
#            - name: WHITELIST_REGISTRIES
#              value: "docker.io,gcr.io"
#          ports:
#            - containerPort: 443
#          volumeMounts:
#            - name: webhook-certs
#              mountPath: /etc/webhook/certs
#              readOnly: true
#      volumes:
#        - name: webhook-certs
#          secret:
#            secretName: webhook-example-certs