apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-example
webhooks:
- name: io.ydzs.admission-registry
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
  clientConfig:
    service:
      namespace: default
      name: webhook-example-svc
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01UQXdOekUxTURZeU5Gb1hEVE13TVRBd05qRTFNRFl5TkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHIyCjluam0xNzcwVytMbk5pZml2MTlDVUxnL3FEODVZRzUzS0RjQVc0Y3lQZUFVZE4rRmhnaWNFZGhnWTYxRktIQ2QKcWJaWnRuWFdsd1BiTGRrdENwRjNjeHFjWW5IZWFyazdPNlVDRlppdmtGTkJzZ1dTM3RXdExwekl1VHBNaEZxQgo4M2ZXYnZSbVZSdFJsMEh2ckJ3VGZ4NWlsQkpyZm16NlV4QnNuNDVmWER4cHp2KzYrbXo0ZTNjbVV1NUJTaEx4CjNCdkQvRHFWUmJiWkVlOTFrM0pLd2E5enlmNXpkUFQyQTNCb0hXQndDbUJOMjZDc095RHQ2WG5Mam5zdjNLTmcKRVdFZFNlZFB0cTBMMS9ZdlR2WHNoeWVoMVc4aHpDOWs2UmxEbDd6Nm9NQ2FGbWpjdHJwVU1vYWRFcmdacGRZUApFMVljdFlGWFRpY3VDYlEwRWU4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSUnVWTTFMYnl0bDR2WWp0QTVLenRJcFZlL2dqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFOSHlUNVo3bwo3WkJyV0psTnlXSGFVclk2ZFhGNjVUNEpGeFR5MmNwcDNwWE5NbEZmQ3FWQXpGc2JHblZJNHlIUDQ3RDJCREtlCjFaaUhCK1NIcExrWE5kRWI0Y1Y5MU9GdkdIVFNiUmVXcUUrdkxCYlF5OTJOQ0JEL1VFRmZ5bzVMR2JSRjg1bksKb3pKRTMvQkppb1d4RTVQaDRmS0VBNDdUMVBZM1BsR3U5emxYbEVGU3I0Ui9xWnV0M0dpa0thandlRGprTGNKYgo1MEZvaHZUTHpQSlN2TnFCN1RqVm84RTR5SGtFZTh2Z3hGbkMybFQxd09nRi82WWhyaWU1VFFmMUdrTWtSYjdQCnV6bG1xYkhCYXJkNHhFazllNzBwK0xBTzJna1FIR0JkREwrZTNXaUE4MnNjRDUwZWVOVTJMdnpVaVdFUnY1ZDkKMXloKy9teFRWd2JmL3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  admissionReviewVersions: ["v1"]
  sideEffects: None
